m4jidb_social_media/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profileauth/', include('profileauth.urls', namespace='profileauth')),
    path('profileauth/accounts/', include('allauth.urls')),
    path('social/', include('social.urls', namespace='social')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileauth/urls.py
from django.urls import path, include
from . import views


app_name = 'profileauth'

urlpatterns = [
    path('profile/', views.Profile.as_view(), name='profile'),
    path('account-information/', views.AccountInformation.as_view(), name='account_information'),
    path('account-information/edit/', views.AccountInformationEditView.as_view(), name='account_information_edit'),
]

social/urls.py
from django.urls import path
from . import views


app_name = 'social'

urlpatterns = [
    path('post/create/', views.PostCreateView.as_view(), name='post_create'),
    path('post/<slug:slug>/edit/', views.PostUpdateView.as_view(), name='post_edit'),
    path('post/<slug:slug>/detail/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/<slug:slug>/add_comment/', views.CommentCreateView.as_view(), name='add_comment'),
    path('post/list/', views.PostListView.as_view(), name='post_list'),
    path('post/<slug:slug>/like/', views.like_post, name='like_post'),
]

profileauth/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django_resized import ResizedImageField


class User(AbstractUser):
    """
    User model that extends the AbstractUser model from Django's auth system.
    Additional fields include phone, bio, birthday, address, country, state, city, and deleted_reason.
    """
    # User's phone number
    phone = models.CharField(max_length=11, null=True, blank=True)

    # User's biography
    bio = models.TextField(blank=True)

    # User's birthday
    birthday = models.DateField(null=True, blank=True)

    # User's address
    address = models.TextField(blank=True)

    # User's country
    country = models.CharField(max_length=200, blank=True)

    # User's state
    state = models.CharField(max_length=200, blank=True)

    # User's city
    city = models.CharField(max_length=200, blank=True)

    # Reason for user deletion
    deleted_reason = models.TextField(null=True, blank=True)

    @property
    def full_name(self) -> str:
        """Returns the full name of the user."""
        return f"{self.first_name} {self.last_name}"

    @property
    def location(self) -> str:
        """Returns the location of the user."""
        return f"{self.city}, {self.state}, {self.country}"

    def __repr__(self) -> str:
        """Returns a string representation of the user."""
        return f"<User: {self.username}>"

    class Meta:
        # Order users by date joined
        ordering = ['-date_joined']

        # Indexes for faster query performance
        indexes = [
            models.Index(fields=['username']),
            models.Index(fields=['email']),
        ]

        # Verbose name for admin site
        verbose_name = "User"
        verbose_name_plural = "Users"


class ProfileImage(models.Model):
    """
    ProfileImage model that represents a user's profile image.
    """
    # Foreign key to a User model
    profile = models.ForeignKey(User, on_delete=models.CASCADE, related_name="profile_images")

    # Resized image field
    image_file = ResizedImageField(
        size=[500, 500],
        crop=['middle', 'center'],
        quality=75,
        upload_to='profile_img/',
        blank=True,
    )

    # Alt text for image
    alt = models.CharField(max_length=250, blank=True)

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    deleted_at = models.DateTimeField(auto_now=True)

    class Meta:
        # Order images by creation date
        ordering = ['-created_at']

        # Index for faster query performance
        indexes = [
            models.Index(fields=['-created_at'])
        ]

        # Verbose name for admin site
        verbose_name = "ProfileImage"
        verbose_name_plural = "ProfileImages"

    def delete(self, *args, **kwargs):
        """Deletes the image file before deleting the model instance."""
        storage, path = self.image_file.storage, self.image_file.path
        storage.delete(path)
        super().delete(*args, **kwargs)

    def __str__(self) -> str:
        """Returns a string representation of the profile image."""
        return self.alt if self.alt else "None"

profileauth/forms.py
from .models import User, ProfileImage
from django import forms
from allauth.account.forms import SignupForm


class AccountInformationEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'username', 'first_name', 'last_name',
            'bio', 'birthday', 'country', 'state', 'city', 'address'
        )


class ProfileImageForm(forms.ModelForm):
    class Meta:
        model = ProfileImage
        fields = ['image_file']


class CustomSignupForm(SignupForm):
    phone = forms.CharField(max_length=11, required=True, widget=forms.TextInput(attrs={'placeholder': 'Phone Number'}))

    def save(self, request):
        user = super(CustomSignupForm, self).save(request)
        user.phone = self.cleaned_data['phone']
        user.save()
        return user

profileauth/views.py
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import AccountInformationEditForm
from .models import User, ProfileImage
from django.views.generic.edit import FormMixin


class Profile(LoginRequiredMixin, generic.TemplateView):
    """
    Profile view that requires login.
    """
    template_name = 'profile/profile.html'


class AccountInformation(LoginRequiredMixin, generic.TemplateView):
    """
    Account information view that requires login.
    """
    template_name = 'profile/account_information.html'

    def get_context_data(self, **kwargs):
        """
        Get context data for the template.
        """
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context['profile_images'] = user.profile_images.all()
        return context


class AccountInformationEditView(LoginRequiredMixin, generic.UpdateView, FormMixin):
    """
    Account information edit view that requires login.
    """
    model = User
    form_class = AccountInformationEditForm
    template_name = 'profile/account_information_edit.html'
    success_url = reverse_lazy('profileauth:account_information')

    def __init__(self, *args, **kwargs):
        """
        Initialize the view.
        """
        super().__init__(*args, **kwargs)
        self.object = None

    def get_object(self, queryset=None):
        """
        Get the object this view is displaying.
        """
        return self.request.user

    def get(self, request, *args, **kwargs):
        """
        Handle GET requests.
        """
        self.object = self.get_object()
        form = self.get_form()
        profile_images = self.object.profile_images.all()
        return self.render_to_response(
            self.get_context_data(form=form, profile_images=profile_images)
        )

    def post(self, request, *args, **kwargs):
        """
        Handle POST requests.
        """
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        """
        If the form is valid, save the associated model.
        """
        form.save(self.request)
        response = super().form_valid(form)
        self._process_profile_images()
        return response

    def _process_profile_images(self):
        """
        Process profile images.
        """
        self._update_existing_images()
        self._add_new_images()
        self._delete_images()

    def _update_existing_images(self):
        """
        Update existing images.
        """
        for image in self.object.profile_images.all():
            alt_name = f"image_{image.id}_alt"
            if alt_name in self.request.POST:
                image.alt = self.request.POST[alt_name]
                image.save()

    def _add_new_images(self):
        """
        Add new images.
        """
        new_images = self.request.FILES.getlist('new_images')
        for image_file in new_images:
            ProfileImage.objects.create(profile=self.object, image_file=image_file)

    def _delete_images(self):
        """
        Delete images.
        """
        deleted_images = self.request.POST.getlist('deleted_images')
        for image_id in deleted_images:
            image = ProfileImage.objects.get(id=image_id)
            image.delete()

profileauth/templates/profile/account_information.html
{% extends 'parent/base.html' %}
{% load account %}

{% block title %}
    account-information
{% endblock %}

{% block content %}
    <h2>Account information</h2>

    <div>
        {% for profile_image in profile_images %}
            <img src="{{ profile_image.image_file.url }}" alt="{{ profile_image.alt }}" style="height: 100px">
        {% empty %}
            <p>No Photo</p>
        {% endfor %}

    <p><strong>Username:</strong> {{ user.username }}</p>
    <p><strong>First Name:</strong> {{ user.first_name }}</p>
    <p><strong>Last Name:</strong> {{ user.last_name }}</p>
    <p><strong>Bio:</strong> {{ user.bio }}</p>
    <p><strong>Birthday:</strong> {{ user.birthday }}</p>
    <p><strong>Country:</strong> {{ user.country }}</p>
    <p><strong>State:</strong> {{ user.state }}</p>
    <p><strong>City:</strong> {{ user.city }}</p>
    <p><strong>Address:</strong> {{ user.address }}</p>

    <a href="{% url 'profileauth:account_information_edit' %}">
        <button type="button">Edit</button>
    </a>
    </div>

    <div>
        <p><strong>Email:</strong> {{ user.email }}</p>

        <a href={% url 'account_email' %}>
            <button type="button">Edit</button>
        </a>
    </div>

    <div>
        <p><strong>Phone Number:</strong> {{ user.phone }}</p>

        <a href=#>
            <button type="button">Edit</button>
        </a>
    </div>

    <div>
        <p><strong>Password:</strong>**********</p>

        <a href={% url 'account_reset_password' %}>
            <button type="button">Reset Password</button>
        </a>
        <br>
        <a href={% url 'account_change_password' %}>
            <button type="button">Change Password</button>
        </a>
    </div>

{% endblock %}

profileauth/templates/profile/account_information_edit.html
{% extends 'parent/base.html' %}

{% block title %}
    Edit Account Information
{% endblock %}

{% block content %}
    <h2>Edit Account Information</h2>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <h3>Edit Profile Images</h3>
        {% for profile_image in profile_images %}
            <label for="image_{{ profile_image.id }}_alt">Alt for Image {{ profile_image.id }}:</label>
            <label>
                <input type="text" name="image_{{ profile_image.id }}_alt" value="{{ profile_image.alt }}" />
            </label>
            <img src="{{ profile_image.image_file.url }}" alt="{{ profile_image.alt }}" style="height: 100px">
            <label>
                <input type="checkbox" name="deleted_images" value="{{ profile_image.id }}">
            </label> Remove
            <br>
        {% endfor %}

        <h3>Add New Profile Images</h3>
        <input type="file" name="new_images" multiple>
        <br>

        <button type="submit">Update Information</button>
    </form>

    <a href="{% url 'profileauth:account_information' %}">Back to Account Information</a>
{% endblock %}

profileauth/templates/profile/profile.html
{% extends 'parent/base.html' %}

{% block title %}
    Profile
{% endblock %}

{% block content %}
    <h2>Your Profile</h2>
    <br>
    <h3><a href="{% url 'profileauth:account_information' %}">Account information</a></h3>
    <h3><a href="#">Posts</a></h3>
    <h3><a href="#">Tickets</a></h3>
{% endblock %}