m4jidb_social_media/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profileauth/', include('profileauth.urls', namespace='profileauth')),
    path('profileauth/accounts/', include('allauth.urls')),
    path('social/', include('social.urls', namespace='social')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileauth/urls.py
from django.urls import path, include
from . import views


app_name = 'profileauth'

urlpatterns = [
    path('profile/', views.Profile.as_view(), name='profile'),
    path('account-information/', views.AccountInformation.as_view(), name='account_information'),
    path('account-information/edit/', views.AccountInformationEditView.as_view(), name='account_information_edit'),
]

social/urls.py
from django.urls import path
from . import views


app_name = 'social'

urlpatterns = [
    path('post/create/', views.PostCreateView.as_view(), name='post_create'),
    path('post/<slug:slug>/edit/', views.PostUpdateView.as_view(), name='post_edit'),
    path('post/<slug:slug>/detail/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/<slug:slug>/add_comment/', views.CommentCreateView.as_view(), name='add_comment'),
    path('post/list/', views.PostListView.as_view(), name='post_list'),
    path('post/<slug:slug>/like/', views.like_post, name='like_post'),
]

social/forms.py
from django import forms
from .models import Comment,  Post


class PostForm(forms.ModelForm):
    images = forms.FileField(required=False)

    class Meta:
        model = Post
        fields = ['title', 'content', 'categories', 'tags']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']  # Add other fields as needed

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['content'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Enter your comment here'})

social/templates/partials/footer.html
footer

social/templates/partials/header.html
{% load i18n %}
{% load account %}
{% load templatetags %}

{% if user.is_authenticated %}
    {% with request.user|last_image as image %}
        <a href="{% url 'profileauth:profile' %}">
            {# Display the user's last image if it exists, otherwise display a default image #}
            {% if image %}
                <img src="{{ image.image_file.url }}" alt="{{ image.alt }}" style="height: 50px">
            {% else %}
                <img
                    src="/media/profile_img/profile_default_image.jpeg"
                    alt="profile_default_image" style="height: 50px"
                >
            {% endif %}
            {# Display links to the user's profile and the logout page #}
            {{ user.username }}
        </a>
        <a href="{% url 'account_logout' %}">{% trans "Log out" %}</a>
    {% endwith %}
{% else %}
    {# If the user is not authenticated, display links to the signup and login pages #}
    <a href="{% url 'account_signup' %}">{% trans "Sign up" %}</a>
    <a href="{% url 'account_login' %}">{% trans "Log in" %}</a>
{% endif %}

social/templates/partials/navigation.html
navigation