m4jidb_social_media/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profileauth/', include('profileauth.urls', namespace='profileauth')),
    path('profileauth/accounts/', include('allauth.urls')),
    path('social/', include('social.urls', namespace='social')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.urls import path
from . import views


app_name = 'social'

urlpatterns = [
    path('post/create/', views.PostCreateView.as_view(), name='post_create'),
    path('post/<slug:slug>/edit/', views.PostUpdateView.as_view(), name='post_edit'),
    path('post/<slug:slug>/detail/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/<slug:slug>/add_comment/', views.CommentCreateView.as_view(), name='add_comment'),
    path('post/list/', views.PostListView.as_view(), name='post_list'),
    path('post/<slug:slug>/like/', views.like_post, name='like_post'),
]

social/forms.py
from django import forms
from .models import Comment,  Post


class PostForm(forms.ModelForm):
    images = forms.FileField(required=False)

    class Meta:
        model = Post
        fields = ['title', 'content', 'categories', 'tags']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']  # Add other fields as needed

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['content'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Enter your comment here'})

social/templates/social/comment_create.html
{% extends 'parent/base.html' %}

{% block content %}
  <h2>Add a Comment</h2>
  <form method="post" action="{% url 'social:add_comment' slug=slug %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit Comment</button>
  </form>

  <a href="{% url 'social:post_detail' slug=slug %}">Cancel and Back to Post Detail</a>
{% endblock %}

social/templates/social/post_create.html
{% extends 'parent/base.html' %}

{% block title %}
    Post Create
{% endblock %}

{% block content %}
    <h2>Create a New Post</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <label for="id_images">Upload Images (optional):</label>
        {{ form.images }}
        <button type="submit">Create Post</button>
    </form>

    <a href="{% url 'social:post_list' %}">Back to Post List</a>
{% endblock %}

social/templates/social/post_detail.html
{% extends 'parent/base.html' %}

{% block title %}
    Post Detail
{% endblock %}

{% block content %}

    {# post's title #}
    <h1>{{ post.title }}</h1>

    {# post's images #}
    {% for image in post.post_images.all %}
    <img src="{{ image.image_file.url }}" alt="{{ image.alt }}" />
    {% endfor %}

    {# post's content #}
    <p>Content: {{ post.content }}</p>

    {# post's author #}
    <p>Author: {{ post.author.username }}</p>

    {# post's published date #}
    <p>Published at: {{ post.published_at }}</p>

    {# post's Categories #}
    <p>
        Categories: {% for category in post.categories.all %}
            {{ category.name }}{% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>

    {# post's tags #}
    <p>Tags: {{ post.tags.all|join:", " }}</p>

    {# post's likes #}
    <p>Likes: <span id="likes-count">{{ post.likes.count }}</span></p>

    {# button for like post #}
    {% if user.is_authenticated %}
    <form id="like-post-form" method="post" data-url="{% url 'social:like_post' post.id %}">
    {% csrf_token %}
    <input type="submit" value="Like">
    </form>
    {% endif %}

    {# post's comments #}
    <h2>Comments</h2>
    {% for comment in comments %}
    <p>{{ comment.content }}</p>
    <p>Author: {{ comment.author.username }}</p>
    <p>Likes: {{ comment.likes.count }}</p>

    {# comment's likes #}


    {# button for like comment #}
    {% if user.is_authenticated %}
    <form method="post" action="{% url 'social:like_comment' comment.id %}">
    {% csrf_token %}
    <input type="submit" value="Like">
    </form>
    {% endif %}
    {% endfor %}

    {# field for add comment #}
    {% if user.is_authenticated %}
    <h3>Add a Comment</h3>
    <form method="post" action="{% url 'social:add_comment' post.id %}">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <input type="submit" value="Submit">
    </form>
    {% endif %}

{% endblock %}

social/templates/social/post_list.html
{% extends 'base.html' %}

{% block content %}
  <h2>Post List</h2>
  <ul>
    {% for post in posts %}
      <li>
        <h3><a href="{% url 'post_detail' slug=post.slug %}">{{ post.title }}</a></h3>
        <p>{{ post.content|truncatewords:50 }}</p>
        <p>Published on {{ post.published_at }}</p>
        <p>Author: {{ post.author.username }}</p>
        <p>Category: {{ post.category.name }}</p>
        <p>Tags: {{ post.tags.all|join:", " }}</p>
        <!-- Add more details as needed -->
      </li>
    {% endfor %}
  </ul>

  {% if is_paginated %}
    <div class="pagination">
      <span class="step-links">
        {% if posts.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ posts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
          Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
        </span>

        {% if posts.has_next %}
          <a href="?page={{ posts.next_page_number }}">next</a>
          <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
      </span>
    </div>
  {% endif %}
{% endblock %}

social/templates/social/post_update.html
{% extends 'base.html' %}

{% block content %}
  <h2>Edit Post - {{ object.title }}</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save Changes</button>
  </form>

  <a href="{% url 'post_detail' slug=object.slug %}">Cancel and Back to Post Detail</a>
{% endblock %}